### ISSUE TITLE
Make Include parse variable expressions

### ISSUE THREAD

**Issue by divillysausages** [docs/liquid#42]
If you have an include tag that uses tokens, like this:

`{% include {{ "foo" | prepend: site.somethingElse }} %}`

or

`{% include {{ page.url }} %}`

the token isn't parsed. Instead, it'll try to load the file "foo.html" or "page.html", resulting in a bad path (I'm using post urls and replacing parts to include post specific content).

Using tokens inside include tags (and possibly all tags?) works on jekyll liquid.

I was looking at the system of Liquid.Block to see if I could hook something in there, but I'm not 100% on how the liquid code is parsed - I guess it'll look for the blockDelimiter, but setting it as `%}` (the end of the include tag) doesn't work either.

Any pointers would be appreciated, thanks

**Comment by sirlantis** [comment]
The current `include` implementation doesn't support variables (but rather the form `include somefile.html`).

An example of how to parse variables would be in [assign.coffee](https://github.com/sirlantis/liquid-node/blob/master/src/liquid/tags/assign.coffee)

---

Independent of that your syntax is definitely off. Looking at [include.rb](https://github.com/Shopify/liquid/blob/master/lib/liquid/tags/include.rb) it should be

`{% include "foo" | prepend: site.somethingElse %}`
or
`{% include page.url %}`

But as mentioned before, `include` currently doesn't support that.

**Comment by divillysausages** [comment]
Hm, this is the code that I'm using in my current Jekyll setup (jekyll 2.0.3):

```{% include {{ page.path | replace:'_posts/','' | prepend: "comments/" }} %}```

Basically I use it to include comments for a post, the comments file being in _includes/comments/NAME_OF_POST. This currently works, so I'm guessing jekyll liquid does parse tokens, or does a pre-pass to resolve tokens before treating tags? You'd be in a better situation than me to say otherwise, but looking at include.rb, I'm leaning towards the first one.

I'll see if I can work something out via the assign implementation - it's the last step I need to get a "nodified" Jekyll implementation running :)

**Comment by divillysausages** [comment]
I assigned the variable part (using the ```{% include %}``` syntax in the comment above) to a variable like so:

```this.filepathVar = new Liquid.Variable(markup);```

but when I render it later in the ```Include.prototype.render``` method, it doesn't seem to pick up the ```page``` variable in the context, even though elsewhere is fine (e.g. using ```<h1>{{ page.title }}</h1>``` to render the page title). The ```context``` object passed looks something like:

```
Context Context {
  environments:
   [ { site: [Object], page: [Object], content: '...' },
     {} ],
  scopes: [ {} ],
  registers: {},
  errors: [],
  rethrowErrors: true,
  strainer: { context: [Circular] } }
```

If I print out the ```page``` object in ```context.environments```, it's something like this:

```
Page:  Content {
  path: 'C:\\...\\testWeb\\dev\\_posts\\2016-01-17-some-page.html',
  frontMatter:...
```

Am I missing something? Is ```Liquid.Variable``` the right thing to use? This is the way I saw ```assign``` doing it.

**Comment by divillysausages** [comment]
OK, got it working by removing the ```{{ }}``` from the markup. This is the solution I'm using (JS, cause I don't know CoffeeScript) - it doesn't handle passing variables though, as shown here: http://jekyllrb.com/docs/templates/#includes

```
module.exports = Include = (function(superClass) {
    var Syntax, SyntaxVar, SyntaxHelp;

    extend(Include, superClass);

    Syntax = /([a-z0-9\/\\_-]+)/i;
	SyntaxVar = /\{\{\s*(.*)\s*\}\}/i;

    function Include(template, tagName, markup, tokens) {
	  var matchVar = SyntaxVar.exec(markup); // check for vars
	  if( matchVar )
	  {
		this.template = template; // we'll need this for later to load the file
	  	this.filepathVar = new Liquid.Variable(matchVar[1]);
	  }
	  else
	  {
		var match = Syntax.exec(markup);
		if (!match) {
			throw new Liquid.SyntaxError(SyntaxHelp);
		}
		this.filepath = match[1];
		this.subTemplate = template.engine.fileSystem.readTemplateFile(this.filepath).then(function(src) {
			return template.engine.parse(src);
		});
	  }
      Include.__super__.constructor.apply(this, arguments);
    }

    Include.prototype.render = function(context) {
		
		// if we have a filepathVar, then we need to render our var to get the
		// name of the content that we're loading
		if( this.filepathVar )
		{
			var incl = this;
			return this.filepathVar.render(context).then(function( path ){
				
				// remove any trailing filetype
				if( path.indexOf( "." ) != -1 )
					path = path.substring( 0, path.indexOf( "." ) );
					
				 // load the file
				 return incl.template.engine.fileSystem.readTemplateFile(path).then(function(src) {
					 
					// get our template to parse the included file, then render
					return incl.template.engine.parse(src).then(function(i){
						return i.render( context );
					})
				});
			});
			
		}
		
		// from this point on, it's a normal include		
		return this.subTemplate.then(function(i) {
			return i.render(context);
		});
    };

    return Include;

  })(Liquid.Tag);
```

Basically, I match the ```markup``` with a variable regex, and if it passes, I push the template loading etc to the render stage.

**Comment by divillysausages** [comment]
I've updated the JS to handle passing variables to the include, as well as passing liquid tags in the include variables - they get rendered first before the main include file.

````
// Generated by CoffeeScript 1.10.0
(function() {
  var Include, Liquid,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Liquid = require("../../liquid");

  module.exports = Include = (function(superClass) {
    var Syntax, SyntaxLiquidVar, SyntaxHelp, SyntaxVars;

    extend(Include, superClass);

    Syntax = /([a-z0-9\/\\_-]+)/i;
	SyntaxLiquidVar = /^\{\{\s*(.*)\s*\}\}/i;
	SyntaxVars = /([a-zA-Z\-_]+)="([^"]+)"/g;

    function Include(template, tagName, markup, tokens) {

		// get any tokens
		this.tokens = {};
		var vars = markup.match( SyntaxVars );
		if( vars )
		{
			// if we have something it'll be in the form 'key="var"'
			var len = vars.length;
			for( var i = 0; i < len; i++ )
			{
				var idx = vars[i].indexOf( '=' );
				var key = vars[i].substring( 0, idx );
				var val = vars[i].substring( idx + 2, vars[i].length - 1 ); // don't take the quote marks with the val
				this.tokens[key] = val;
			}
		}

		var matchVar = SyntaxLiquidVar.exec(markup); // check for vars
		if( matchVar )
		{
			this.template = template; // we'll need this for later to load the file
			this.filepathVar = new Liquid.Variable(matchVar[1]);
		}
		else
		{
			var match = Syntax.exec(markup);
			if (!match) {
				throw new Liquid.SyntaxError(SyntaxHelp);
			}
			this.filepath = match[1];
			this.subTemplate = template.engine.fileSystem.readTemplateFile(this.filepath).then(function(src) {
				return template.engine.parse(src);
			});
		}
		Include.__super__.constructor.apply(this, arguments);
    }

	// renders any liquid tokens for the include
	Include.prototype.renderTokens = function( context, thenFunc ) {

		// we loop through our tokens finding any that need to be converted. Once they're converted,
		// we move on to render the rest of the include
		for( var key in this.tokens )
		{
			var val = this.tokens[key];
			var match = SyntaxLiquidVar.exec( val );
			if( match )
			{
				var liquidVar = new Liquid.Variable( match[1] );
				var incl = this;
				return liquidVar.render( context ).then( function( text ) {
					incl.tokens[key] = text;
					return incl.renderTokens( context, thenFunc ); // recurse
				} );
			}
		}
		return thenFunc.call( this, context );
	}

	// renders the include itself
	Include.prototype.renderInclude = function( context ) {

		// set any variables
		var len = context.environments.length;
		for( var i = 0; i < len; i++ )
		{
			if( context.environments[i].site != null )
				context.environments[i].include = this.tokens;
		}
	
		// if we have a filepathVar, then we need to render our var to get the
		// name of the content that we're loading
		if( this.filepathVar )
		{
			var incl = this;
			return this.filepathVar.render(context).then(function( path ){
				
				// remove any trailing filetype
				if( path.indexOf( "." ) != -1 )
					path = path.substring( 0, path.indexOf( "." ) );
					
				// load the file
				return incl.template.engine.fileSystem.readTemplateFile(path).then(function(src) {
					
					// get our template to parse the included file, then render
					return incl.template.engine.parse(src).then(function(i){
						return i.render( context );
					})
				});
			});
			
		}
		
		// from this point on, it's a normal include		
		return this.subTemplate.then(function(i) {
			return i.render(context);
		});
	}

    Include.prototype.render = function(context) {

		// check if we need to render any of our tokens
		return this.renderTokens( context, this.renderInclude );
    };

    return Include;

  })(Liquid.Tag);

}).call(this);

//# sourceMappingURL=include.js.map
`````

You can now include files like:

````
{% include some_incl.html %}
````

or 

````
{% include {{ page.path | replace:'_posts/','' | prepend: "comments/" }} %}
````

or 

````
{% include some_incl.html key="var" %} // can access with {{ include.key }}
````

or

````
{% include some_incl.html path="{{ '/path/to/file' | prepend: site.url }}" %} // include.path will be an absolute path
````

**Comment by pburrows** [comment]
Has this fix been included in the project? The code in include.js does not seem to match:
https://github.com/liquid-lang/liquid-node/blob/master/lib/liquid/tags/include.js

**Comment by divillysausages** [comment]
The code that I posted was what I changed in the final converted output to get it working on my end in a messy fix. I don't know coffescript and at the time had no time to learn it and the project layout just to submit a patch

**Comment by pburrows** [comment]
Hm. It seems the code base has been recently migrated from CoffeeScript to JavaScript (https://github.com/liquid-lang/liquid-node/pull/71) (just this past March, I know your code is from 2016!). Might be worth opening a PR if you have time?
