### ISSUE TITLE
include doesn't support `with` keyword? 

### ISSUE THREAD

**Issue by ansyral** [docs/liquid#67]
Hi, I'm using `include` tag to include some snippet and I'd like to pass parameters using `with`, seems it isn't supported now?

**Comment by ansyral** [comment]
Besides, not sure why, the following template
```
color: `{% include 'report_method_table' children = failedTests %}`
color: `{% include 'report_method_table' children = AllTests %}`
color: `{% include 'report_method_table' children = passedTests %}`
```
three snippets are rendered to same content, any idea why?

**Comment by GustavoRPS** [comment]
Hi @ansyral did you solve this issue? I'm going through something similar and your feedback will be welcome.
